# Generated by Django 3.0b1 on 2019-12-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191223_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'Github'), ('kakao', 'Kakao'), ('line', 'Line'), ('twitter', 'Twitter')], default='email', max_length=20),
        ),
    ]
