# Generated by Django 3.0b1 on 2019-12-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_line_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='line_sub',
        ),
    ]
