language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python app/manage.py test
before_install:
  - openssl aes-256-cbc -K $encrypted_e67abccd455b_key -iv $encrypted_e67abccd455b_iv -in .env.enc -out .env -d
