language: python
python:
  - "3.6"
install:
  - pip3 install -r requirements.txt
script:
  - python3 manage.py test
before_install:
  - openssl aes-256-cbc -K $encrypted_e67abccd455b_key -iv $encrypted_e67abccd455b_iv -in .env.enc -out .env -d
branches:
  only:
    - master
before_deploy:
  - zip -r airbnb *
  - mkdir -p deploy
  - mv airbnb.zip deploy/airbnb.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    region: ap-northeast-1
    skip_cleanup: true
    local_dir: deploy
    wait_until_deployed: true
    on:
      repo: geonwoo-jeong/airbnb-clone
      branch: master
